<?php
/**
 * @var \Fabfuel\Prophiler\Toolbar\Formatter\BenchmarkFormatterInterface $benchmarkFormatter
 */
?>
<div class="panel-group panel-collapse collapse" id="<?= $dataCollector->getTitle() ?>" role="tablist" style="margin-top: 5px;">

    <?php foreach ($dataCollector->getData() as $dataName => $data): ?>

    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-<?= $dataName ?>">
            <h4 class="panel-title" style="font-size: 1.1em">
                <a class="collapsed" data-toggle="collapse" data-parent="#benchmarks" href="#collapse-<?= $dataName ?>" aria-expanded="false" aria-controls="collapseTwo">
                    <?= $dataName ?>
                </a>
            </h4>
        </div>
        <div id="collapse-<?= $dataName ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<?= $dataName ?>">
            <div class="panel-body">
                <json style="white-space: pre;"><?= json_encode($data); ?></json>
            </div>
        </div>
    </div>

    <?php endforeach; ?>
</div>
