<?php
/**
 * @var \Fabfuel\Prophiler\ProfilerInterface $profiler
 */
?><style>
    <?php echo file_get_contents(__DIR__ . '/css/screen.css'); ?>
</style>

<div id="prophiler">

    <div class="toolbar">

        <nav class="navbar navbar-default" role="navigation" style="margin-bottom: 0px;">
            <div class="container-fluid">

                <a class="navbar-brand">Phalcon Dev Toolbar</a>

                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#">
                                <?php if ($profiler->getDuration() * 1000 < 2): ?>
                                    <span class="label label-success">
                                <?php elseif ($profiler->getDuration() * 1000 < 5): ?>
                                    <span class="label label-warning">
                                <?php else: ?>
                                    <span class="label label-danger">
                                <?php endif; ?>
                                    <span class="glyphicon glyphicon-time"></span> <?php printf('%.3f ms ', $profiler->getDuration() * 1000) ?>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="label label-primary"><span class="glyphicon glyphicon-tasks"></span> <?php printf('%.3f MB', memory_get_peak_usage() / 1024 / 1024) ?></span>
                            </a>
                        </li>
                        <li><a class="collapsed" data-toggle="collapse" data-parent="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="collapseTwo" href="#benchmarks">
                                <span class="glyphicon glyphicon-dashboard"> Benchmarks
                        </a></li>

                        <?php foreach ($dataCollectors as $dataCollector): ?>
                            <li><a class="collapsed" data-toggle="collapse" data-parent="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="collapseTwo" href="#<?= $dataCollector->getTitle() ?>">
                                    <span class="glyphicon glyphicon-<?= $dataCollector->getIcon() ?>"> <?= $dataCollector->getTitle() ?></a></li>
                        <?php endforeach; ?>
                    </ul>
            </div>
        </nav>

        <div class="panel-group panel-collapse " id="benchmarks" role="tablist" style="margin-top: 5px;">
            <?php $this->partial('partials/table', ['profiler' => $profiler]); ?>
        </div>

        <?php foreach ($dataCollectors as $dataCollector): ?>
            <?php $this->partial('partials/datacollector'); ?>
        <?php endforeach; ?>
    </div>
</div>

<script>
	if (!window.jQuery) {
		document.write('<script src="//code.jquery.com/jquery-2.1.1.min.js"><\/script>');
	}
    window.addEventListener("load", function () {
        $('json').each(function (index, el) {
            el.innerHTML = JSON.stringify(JSON.parse(el.innerHTML), null, '\t');
        });
    });
</script>
