<?php if (!is_null($data) && $data !== []):?>
    <dt><?= $dataName ?></dt>
    <dd>
        <?php if (is_array($data)): ?>
            <?php if (empty($json)): ?>
                <?php $this->partial('partials/details/data/array', ['data' => $data]); ?>
            <?php else: ?>
                <?php $this->partial('partials/details/data/json', ['data' => $data]); ?>
            <?php endif; ?>
        <?php elseif (is_string($data)): ?>
            <?= nl2br($data) ?>
        <?php else: ?>
            <?php if (extension_loaded('xdebug')): ?>
                <?php var_dump($data); ?>
            <?php else: ?>
                <pre>
                    <?php
                    ob_start();
                    var_dump($data);
                    echo htmlentities(ob_get_clean());
                    ?>
                </pre>
            <?php endif; ?>
        <?php endif; ?>
    </dd>
<?php endif; ?>
